In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('credit_customers.csv')

In [3]:
data.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad

In [7]:
# Display all column names in the dataframe
data.columns

# Show detailed information about the dataframe including data types and non-null values
data.info()

# Display the dimensions of the dataframe (rows, columns)
data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   checking_status         1000 non-null   object
 1   duration                1000 non-null   float64
 2   credit_history          1000 non-null   object
 3   purpose                 1000 non-null   object
 4   credit_amount           1000 non-null   float64
 5   savings_status          1000 non-null   object
 6   employment              1000 non-null   object
 7   installment_commitment  1000 non-null   float64
 8   personal_status         1000 non-null   object
 9   other_parties           1000 non-null   object
 10  residence_since         1000 non-null   float64
 11  property_magnitude      1000 non-null   object
 12  age                     1000 non-null   float64
 13  other_payment_plans     1000 non-null   object
 14  housing                 1000 non-null   object
 15  existing_credits        1000 non-null   float64
 16  job                     1000 non-null   object
 17  num_dependents          1000 non-null   float64
 18  own_telephone           1000 non-null   object
 19  foreign_worker          1000 non-null   object
 20  class                   1000 non-null   object
dtypes: float64(7), object(14)
memory usage: 164.2+ KB

(1000, 21)

In [ ]:
# Remove unnecessary columns from the dataset
# - checking_status: Account status information not needed for analysis
# - duration: Time duration feature being dropped
# - purpose: Purpose of credit not required for current analysis
# - personal_status: Personal status information being excluded
data.drop(columns=[
    'checking_status',
    'duration',
    'purpose',
    'personal_status'
], inplace=True)

In [10]:
data.columns

Index(['credit_history', 'credit_amount', 'savings_status', 'employment',
       'installment_commitment', 'other_parties', 'residence_since',
       'property_magnitude', 'age', 'other_payment_plans', 'housing',
       'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='object')

In [11]:
data.shape

(1000, 17)

In [12]:
data

,credit_history,credit_amount,savings_status,employment,installment_commitment,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,critical/other existing credit,1169.0,no known savings,>=7,4.0,none,4.0,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,existing paid,5951.0,<100,1<=X<4,2.0,none,2.0,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,critical/other existing credit,2096.0,<100,4<=X<7,2.0,none,3.0,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,existing paid,7882.0,<100,4<=X<7,2.0,guarantor,4.0,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,delayed previously,4870.0,<100,1<=X<4,3.0,none,4.0,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,existing paid,1736.0,<100,4<=X<7,3.0,none,4.0,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,good
996,existing paid,3857.0,<100,1<=X<4,4.0,none,4.0,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
997,existing paid,804.0,<100,>=7,4.0,none,4.0,car,38.0,none,own,1.0,skilled,1.0,none,yes,good
998,existing paid,1845.0,<100,1<=X<4,4.0,none,4.0,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,bad
999,critical/other existing credit,4576.0,100<=X<500,unemployed,3.0,none,4.0,car,27.0,none,own,1.0,skilled,1.0,none,yes,good

In [14]:
# Convert column names to lowercase and replace spaces with underscores for consistent naming convention
data.columns = data.columns.str.lower().str.replace(' ', '_')

In [15]:
data.columns

Index(['credit_history', 'credit_amount', 'savings_status', 'employment',
       'installment_commitment', 'other_parties', 'residence_since',
       'property_magnitude', 'age', 'other_payment_plans', 'housing',
       'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='object')

In [16]:
# Check if there are any duplicate rows in the dataset
# Returns the count of duplicated rows (rows that appear more than once, with only subsequent occurrences counted as duplicates)
data.duplicated().sum()

np.int64(0)

In [17]:
# remove duplicates
data.drop_duplicates(inplace=True)

In [18]:
# check nulls
data.isna().sum()

credit_history            0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [19]:
# remove null rows
data.dropna(inplace=True)

In [20]:
data.shape

(1000, 17)

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   credit_history          1000 non-null   object
 1   credit_amount           1000 non-null   float64
 2   savings_status          1000 non-null   object
 3   employment              1000 non-null   object
 4   installment_commitment  1000 non-null   float64
 5   other_parties           1000 non-null   object
 6   residence_since         1000 non-null   float64
 7   property_magnitude      1000 non-null   object
 8   age                     1000 non-null   float64
 9   other_payment_plans     1000 non-null   object
 10  housing                 1000 non-null   object
 11  existing_credits        1000 non-null   float64
 12  job                     1000 non-null   object
 13  num_dependents          1000 non-null   float64
 14  own_telephone           1000 non-null   object
 15  foreign_worker          1000 non-null   object
 16  class                   1000 non-null   object
dtypes: float64(6), object(11)
memory usage: 132.9+ KB

In [22]:
data

,credit_history,credit_amount,savings_status,employment,installment_commitment,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,critical/other existing credit,1169.0,no known savings,>=7,4.0,none,4.0,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,existing paid,5951.0,<100,1<=X<4,2.0,none,2.0,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,critical/other existing credit,2096.0,<100,4<=X<7,2.0,none,3.0,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,existing paid,7882.0,<100,4<=X<7,2.0,guarantor,4.0,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,delayed previously,4870.0,<100,1<=X<4,3.0,none,4.0,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,existing paid,1736.0,<100,4<=X<7,3.0,none,4.0,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,good
996,existing paid,3857.0,<100,1<=X<4,4.0,none,4.0,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
997,existing paid,804.0,<100,>=7,4.0,none,4.0,car,38.0,none,own,1.0,skilled,1.0,none,yes,good
998,existing paid,1845.0,<100,1<=X<4,4.0,none,4.0,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,bad
999,critical/other existing credit,4576.0,100<=X<500,unemployed,3.0,none,4.0,car,27.0,none,own,1.0,skilled,1.0,none,yes,good

In [23]:
data['employment'].unique()

array(['>=7', '1<=X<4', '4<=X<7', 'unemployed', '<1'], dtype=object)

In [24]:
# Clean the 'employment' column by removing leading/trailing whitespace and converting to lowercase
data['employment'] = data['employment'].str.strip().str.lower()

In [25]:
data['employment'].unique()

array(['>=7', '1<=x<4', '4<=x<7', 'unemployed', '<1'], dtype=object)

In [26]:
# Create a mapping dictionary to convert employment categories to numeric values
# '<1' and 'unemployed' are mapped to 0 years
# '1<=x<4' is mapped to 2 years (midpoint)
# '4<=x<7' is mapped to 5 years (midpoint)
# '>=7' is mapped to 7 years (minimum value)
employment_mapping = {
    '<1': 0,
    '1<=x<4': 2,
    '4<=x<7': 5,
    '>=7': 7,
    'unemployed': 0
}

# Apply the mapping to convert the categorical 'employment' column to numeric values
data['employment'] = data['employment'].map(employment_mapping)

In [27]:
data['employment'].unique()

array([7, 2, 5, 0])

In [28]:
data['employment'].isna().sum()

np.int64(0)

In [29]:
data

,credit_history,credit_amount,savings_status,employment,installment_commitment,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,critical/other existing credit,1169.0,no known savings,7,4.0,none,4.0,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,existing paid,5951.0,<100,2,2.0,none,2.0,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,critical/other existing credit,2096.0,<100,5,2.0,none,3.0,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,existing paid,7882.0,<100,5,2.0,guarantor,4.0,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,delayed previously,4870.0,<100,2,3.0,none,4.0,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,existing paid,1736.0,<100,5,3.0,none,4.0,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,good
996,existing paid,3857.0,<100,2,4.0,none,4.0,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
997,existing paid,804.0,<100,7,4.0,none,4.0,car,38.0,none,own,1.0,skilled,1.0,none,yes,good
998,existing paid,1845.0,<100,2,4.0,none,4.0,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,bad
999,critical/other existing credit,4576.0,100<=X<500,0,3.0,none,4.0,car,27.0,none,own,1.0,skilled,1.0,none,yes,good

In [30]:
# Convert the 'class' column values to binary:
# - 'good' becomes 1
# - any other value becomes 0
data['class'] = data['class'].apply(lambda x: 1 if x == 'good' else 0)

In [31]:
# Count the occurrences of each unique value in the 'class' column
# This helps us understand the distribution of classes in the dataset
data['class'].value_counts()

class
1    700
0    300
Name: count, dtype: int64

In [32]:
data.dtypes

credit_history             object
credit_amount             float64
savings_status             object
employment                  int64
installment_commitment    float64
other_parties              object
residence_since           float64
property_magnitude         object
age                       float64
other_payment_plans        object
housing                    object
existing_credits          float64
job                        object
num_dependents            float64
own_telephone              object
foreign_worker             object
class                       int64
dtype: object

In [33]:
data

,credit_history,credit_amount,savings_status,employment,installment_commitment,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,critical/other existing credit,1169.0,no known savings,7,4.0,none,4.0,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,1
1,existing paid,5951.0,<100,2,2.0,none,2.0,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,0
2,critical/other existing credit,2096.0,<100,5,2.0,none,3.0,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,1
3,existing paid,7882.0,<100,5,2.0,guarantor,4.0,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,1
4,delayed previously,4870.0,<100,2,3.0,none,4.0,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,existing paid,1736.0,<100,5,3.0,none,4.0,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,1
996,existing paid,3857.0,<100,2,4.0,none,4.0,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,1
997,existing paid,804.0,<100,7,4.0,none,4.0,car,38.0,none,own,1.0,skilled,1.0,none,yes,1
998,existing paid,1845.0,<100,2,4.0,none,4.0,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,0
999,critical/other existing credit,4576.0,100<=X<500,0,3.0,none,4.0,car,27.0,none,own,1.0,skilled,1.0,none,yes,1

In [34]:
# Define a list of numerical features to be used in the analysis
# - age: customer's age
# - existing_credits: number of existing credits at this bank
# - num_dependents: number of people being financially supported by the customer
# - residence_since: years at current residence
cols = ['age', 'existing_credits', 'num_dependents', 'residence_since']

In [35]:
data[cols].isna().sum()

age                 0
existing_credits    0
num_dependents      0
residence_since     0
dtype: int64

In [37]:
# Round all values in the specified columns to the nearest integer
data[cols] = data[cols].round()

In [39]:
# Convert specified columns to integer data type
# This ensures numerical operations work correctly and removes any decimal points
data[cols] = data[cols].astype(int)

In [40]:
data[cols].dtypes

age                 int64
existing_credits    int64
num_dependents      int64
residence_since     int64
dtype: object

In [41]:
data

,credit_history,credit_amount,savings_status,employment,installment_commitment,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,critical/other existing credit,1169.0,no known savings,7,4.0,none,4,real estate,67,none,own,2,skilled,1,yes,yes,1
1,existing paid,5951.0,<100,2,2.0,none,2,real estate,22,none,own,1,skilled,1,none,yes,0
2,critical/other existing credit,2096.0,<100,5,2.0,none,3,real estate,49,none,own,1,unskilled resident,2,none,yes,1
3,existing paid,7882.0,<100,5,2.0,guarantor,4,life insurance,45,none,for free,1,skilled,2,none,yes,1
4,delayed previously,4870.0,<100,2,3.0,none,4,no known property,53,none,for free,2,skilled,2,none,yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,existing paid,1736.0,<100,5,3.0,none,4,real estate,31,none,own,1,unskilled resident,1,none,yes,1
996,existing paid,3857.0,<100,2,4.0,none,4,life insurance,40,none,own,1,high qualif/self emp/mgmt,1,yes,yes,1
997,existing paid,804.0,<100,7,4.0,none,4,car,38,none,own,1,skilled,1,none,yes,1
998,existing paid,1845.0,<100,2,4.0,none,4,no known property,23,none,for free,1,skilled,1,yes,yes,0
999,critical/other existing credit,4576.0,100<=X<500,0,3.0,none,4,car,27,none,own,1,skilled,1,none,yes,1

In [42]:
data.head()
data.info()
data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   credit_history          1000 non-null   object
 1   credit_amount           1000 non-null   float64
 2   savings_status          1000 non-null   object
 3   employment              1000 non-null   int64
 4   installment_commitment  1000 non-null   float64
 5   other_parties           1000 non-null   object
 6   residence_since         1000 non-null   int64
 7   property_magnitude      1000 non-null   object
 8   age                     1000 non-null   int64
 9   other_payment_plans     1000 non-null   object
 10  housing                 1000 non-null   object
 11  existing_credits        1000 non-null   int64
 12  job                     1000 non-null   object
 13  num_dependents          1000 non-null   int64
 14  own_telephone           1000 non-null   object
 15  foreign_worker          1000 non-null   object
 16  class                   1000 non-null   int64
dtypes: float64(2), int64(6), object(9)
memory usage: 132.9+ KB

(1000, 17)

In [44]:
# Save the cleaned dataframe to a CSV file without including the index column
data.to_csv('clean_data.csv', index=False)

In [46]:
# Export the cleaned dataframe to an Excel file without including row indices
data.to_excel('clean_excel_data.xlsx', index=False)